# 清华大学源
source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'
# 私有源
source 'https://github.com/kaibuleite/xSpecs.git'

use_frameworks!

platform :ios, '12.0'

target 'xPhotoAlbum_Example' do
  pod 'xPhotoAlbum', :path => '../'

  target 'xPhotoAlbum_Tests' do
    inherit! :search_paths

    
  end
end
